<h2><?php echo __('Total orders placed:') ?> <b><?php echo $this->getData('total_orders_placed') ?></b></h2>
<h2><?php echo __('Total orders completed:') ?> <b><?php echo $this->getData('total_orders_completed') ?></b></h2>
<h2><?php echo __('Order completion rate:') ?> <b><?php echo $this->getData('order_completion_rate') ?>%</b></h2>
<h2><?php echo __('Completed orders value:') ?> <b><?php echo $this->getData('completed_orders_value') ?></b></h2>
<h2><?php echo __('Recovered carts qty:') ?> <b><?php echo $this->getData('recovered_carts_qty') ?></b></h2>
<h2><?php echo __('Recovered carts value:') ?> <b><?php echo $this->getData('recovered_carts_value') ?></b></h2>