<?php
/**
 * @author Evince Team
 * @copyright Copyright (c) 2018 Evince (http://evincemage.com/)
 */
?>

<?php
    $ourPartCategory = $this->getCategory(5);
    $ourPartCategoryUrl = '#';
    if($ourPartCategory->getId()) {
        $ourPartCategoryUrl = $ourPartCategory->getUrl();
    }

    $modelCategory = $this->getCategory(7);
    $modelCategoryUrl = '#';
    if($modelCategory->getId()) {
        $modelCategoryUrl = $modelCategory->getUrl();
    }

?>
<div class="matrix-parts-grid my-trimax col1-layout ">
    <div class="main">
        <div class="trimax-items">
            <ul>
                <li>
                    <div class="details">
                    <a class="title" href="<?php echo $ourPartCategoryUrl ?>"><?= __('OUR PARTS') ?></a>
                        <div class="description">
                            <?= __('Our Genuine parts are proven to enable customers to finish the jobs they started under pressure.') ?>
                        </div>
                        <div class="button">

                            <a class="actions" href="<?php echo $modelCategoryUrl ?>">
                                <?= __('BROWSE BY MODEL') ?>
                            </a>
                        </div>
                    </div>
                </li>
                <li class="odd-item">
                     <div class="details">

                    <?php if (!$block->isLoggedIn()): ?>
                         <a class="title" href="<?php echo $block->getLoginUrl() ?>"><?= __('MY TRIMAX') ?></a>
                            <div class="description">
                                <?= __('To gain access to resources and view your order history,') ?>
                                <a class="signup" href="<?php echo $block->getLoginUrl() ?>"><?= __('sign up') ?></a>
                                <?= __('or') ?>
                                <a class="login" href="<?php echo $block->getRegisterUrl() ?>"><?= __('login') ?></a>
                                <?= __('to your account') ?>
                            </div>
                            <div class="button">
                                <a class="actions" href="<?php echo $block->getLoginUrl() ?>">
                                    <?= __('SIGN UP') ?>
                                </a>
                            </div>
                        </div>
                    <?php else: ?>
                        <a class="title my-trimax-section" href="#"><?= __('MY TRIMAX') ?></a>
                        <div class="description">
                            <?= __('Check our resources and your order history.') ?>
                        </div>
                        <div class="button">
                            <a class="actions" href="<?php echo $block->getMyOrderUrl() ?>">
                                <?= __('My Orders') ?>
                            </a>
                        </div>
                    <?php endif; ?>
                </li>
                <li>
                    <div class="details">
                    <a class="title" href="#"><?= __('IDENTIFY YOUR MOWER') ?></a>

                        <div class="description">
                            <?= __('Not sure which model of mower you own? We\'ve put togther a table to help you identify your make and model.') ?>
                        </div>
                        <div class="button">
                            <a class="actions" href="#">
                                <?= __('VIEW TABLES') ?>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<script>
    require([
        'jquery',
    ], function ($) {
        $(".my-trimax-section").click(function() {
            $('html,body').animate({
                    scrollTop: $("#trimax-menu").offset().top},
                'slow');
        });
    });
</script>
