<?php
/**
 * @author Evince Team
 * @copyright Copyright (c) 2018 Evince (http://evincemage.com/)
 */
?>

<div class="my-trimax col1-layout">
    <div class="main">
        <div class="trimax-items">
            <ul>
                <li>
                    <a class="warranty white service" href="<?php echo $this->getUrl('warranty');?>"><?= __('WARRANTY REGISTRATION') ?></a>
                </li>
                <li>
                    <a class="parts-manual white service" href="<?php echo $this->getUrl('parts-manuals');?>"><?= __('PARTS MANUALS') ?></a>
                </li>
                <li>
                    <a class="operators white service" href="<?php echo $this->getUrl('operators-manual');?>"><?= __('OPERATORS MANUAL') ?></a>
                </li>
                <li>
                    <a class="service-bulletin white service" href="<?php echo $this->getUrl('service-bulletin');?>"><?= __('SERVICE BULLETIN') ?></a>
                </li>
            </ul>
        </div>
    </div>
</div>