<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Abandoned Cart Alerts Pro by Aitoc &reg;') ?></span>
    </div>
    <div>
        <p><?php echo __('Abandoned Cart Alerts Pro by Aitoc helps you recover lost sales by sending automatic abandoned cart alerts to customers.') ?></p>
        <p><a href="http://www.aitoc.com" target="_blank"><?php echo __('Visit Aitoc\'s official page') ?></a></p><br/>
    </div>
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Help and Support') ?></span>
    </div>
    <div>
        <p><?php echo __('Aitoc offers <strong>free email support for life!</strong> If you have any questions about our extension, please <a href="https://support.aitoc.com/index.php?/Tickets/Submit/" target="_blank">contact us</a>.') ?></p>
    </div>
</div>