<?php
/**
 * @author Evince Team
 * @copyright Copyright (c) 2018 Evince (http://evincemage.com/)
 */
?>
<?php if (!$block->isLoggedIn()): ?>
    <div class="account-cart-wrapper">
        <a href="<?php echo $block->getLoginUrl() ?>" class="button login"><?= __('LOGIN') ?></a>
        <a href="<?php echo $block->getRegisterUrl() ?>" class="button register"><?= __('REGISTER') ?></a>
    </div>
<?php endif; ?>
