<script type="text/javascript">
    require([
            'jquery',
            'mage/template',
            'jquery/ui',
            'mage/translate'
        ],
        function ($, mageTemplate) {
            $(document).ready(function() {
                var countryId = $('select[name=country_id]').val();
                var regionId = $('select[name=region_id]').val();
                $.ajax({
                    url: '<?php echo $this->getUrl('multilocationinventory/warehouse/regionlist') ?>',
                    type: 'post',
                    data: {form_key: window.FORM_KEY, country: countryId, region: regionId},
                    dataType: 'json',
                    showLoader: true,
                    success: function (data) {
                        var regionSelector = $('select[name=region_id]');
                        regionSelector.empty();
                        if (data.htmlconent) {
                            regionSelector.closest('.admin__field').show();
                            regionSelector.append(data.htmlconent);
                        } else {
                            regionSelector.append('<option value="" selected="selected">Please select a region, state or province.</option>');
                            regionSelector.change();
                            regionSelector.closest('.admin__field').hide();
                        }
                    }
                });

            });
            $('select[name=country_id]').on('change', function () {
                var countryId = $(this).val();
                $.ajax({
                    url: '<?php echo $this->getUrl('multilocationinventory/warehouse/regionlist') ?>',
                    type: 'post',
                    data: {form_key: window.FORM_KEY, country: countryId},
                    dataType: 'json',
                    showLoader: true,
                    success: function (data) {
                        var regionSelector = $('select[name=region_id]');
                        regionSelector.empty();
                        if (data.htmlconent) {
                            regionSelector.closest('.admin__field').show();
                            regionSelector.append(data.htmlconent);
                        } else {
                            regionSelector.append('<option value="" selected="selected">Please select a region, state or province.</option>');
                            regionSelector.change();
                            regionSelector.closest('.admin__field').hide();
                        }
                    }
                });
            });
        }
    );

</script>