
<script>
    require(["jquery", "jquery/ui", "preorder"], function ($) {
        $('.product-info-main').preorder({
            jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfigPreorder(); ?>,
            jsonText:<?php /* @escapeNotVerified */ echo $block->getJsonConfigPreorderText(); ?>,
            change:<?php /* @escapeNotVerified */ echo $block->getJsonConfigChange(); ?>,
            classes: {
                attributeInput: 'product',
                attributeStock:'stock',
            },
            selectorTag: 'button'
        });
    });
</script>