<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div class="entry-edit fieldset" id="import_validation_container" style="display:none; margin-top:30px">
    <div class="entry-edit-head legend">
        <span class="icon-head head-edit-form fieldset-legend"
            id="import_validation_container_header"><?php /* @escapeNotVerified */ echo __('Validation Results'); ?></span>
    </div><br>
    <div id="import_validation_messages" class="fieldset"><!-- --></div>
</div>
